### ISSUE TITLE
Minecraft server discovers plugin but can't run command.

### ISSUE THREAD

**Issue by AngelAlvarado** [metadaddy/KafkaPlugin#1]
I'm trying to run this plugin. The server loads and enables it (it does not read the map file tho., where should I place the text file?).

`[20:33:43 INFO]: [KafkaCraft] Loading KafkaCraft v1.0`
`[20:33:47 INFO]: [KafkaCraft] Enabling KafkaCraft v1.0`
`[20:33:47 INFO]: [KafkaCraft] Enable`

However, the client does not discover the plugin. This is the output:  `/kafka`- `You don't' have <plugin name>.kafka`.

I placed KafkaCraft.jar in the plugins folder and kafka client (kafka-clients-0.9.0.1.jar) and slf4j(slf4j-api-1.7.22.jar) outside of it. I'm using Spigot 1.10.2

**Comment by metadaddy** [comment]
The maps (world.txt etc) must be packaged into the plugin jar. Make sure you edit `start.sh` to put the slf4j and kafka jars on the classpath.

**Comment by metadaddy** [comment]
You'll also need to op yourself to be able to run the command.

**Comment by AngelAlvarado** [comment]
Thanks. That solved the issue!
